name: Build release artifact
on: push
# on:
#   push:
#     tags:
#       - "*"
jobs:
  # This job runs schematron validation(s) on the file that is passed in
  build-release:
    # Run on ubuntu
    runs-on: ubuntu-latest

    # Checkout repository and its submodules
    steps:
      # Check-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Read Node version from .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - uses: actions/setup-node@v2.3.0
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}

        # Initialize workspace and build a release
      - name: Build release
        run: make init build

      - name: ls dist
        run: ls -l dist

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: dist/validations/ssp.xsl
          prerelease: true
          tag: latest
          token: ${{ secrets.GITHUB_TOKEN }}
