name: Build release artifact
on: push
jobs:
  # This job runs schematron validation(s) on the file that is passed in
  build-release:
    # Run on ubuntu
    runs-on: ubuntu-latest

    # Checkout repository and its submodules
    steps:
      # Check-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Set up the correct version of node using nvm
        uses: dcodeIO/setup-node-nvm@v4

        # Initialize workspace and build a release
      - name: Build release
        run: make init build
