# This action runs unit tests for the OSCAL (schematron) validations to ensure validations
# are working against known samples
name: "OSCAL Validations: Unit Tests"

# Triggered when code is pushed to any branch in a repository
on: push

# the job requires some dependencies to be installed (including submodules), runs the tests, and then reports results
jobs:
  # one job that runs tests
  run-tests:
    # Run on ubuntu
    runs-on: ubuntu-latest

    # Checkout repository and its submodules
    steps:
      # Check-out the repository under $GITHUB_WORKSPACE
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read node version from `.nvmrc` file
        id: nvmrc
        uses: browniebroke/read-nvmrc-action@v1

      - name: Install required node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvmrc.outputs.node_version }}"

      # Initialize the workspace with submodules and dependencies.
      - name: Initialize workspace
        run: make init

      - name: Run test suite
        run: |
          make build-validations
          make test-validations SAXON_CP=~/.m2/repository/net/sf/saxon/Saxon-HE/10.5/Saxon-HE-10.5.jar TEST_DIR=$(pwd)/src/validations/report/test
          make test-web

      # Sets the test report path for visibility
      - name: Publish XSpec Test Results
        uses: mikepenz/action-junit-report@v1
        with:
          report_paths: "**/report/test/*junit.xml"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Publish the test summary as comment on the PR
      - name: Publish XSpec Test Results Summary
        uses: EnricoMi/publish-unit-test-result-action@v1.15
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: XSpec Test Results
          files: "**/report/test/*junit.xml"
          report_individual_runs: true
          deduplicate_classes_by_file_name: false

      - name: Upload Resulting Schematron SVRL Report
        uses: actions/upload-artifact@27bce4eee761b5bc643f46a8dfb41b430c8d05f6 # v2
        with:
          name: fedramp-automation-validation-unit-tests-${{ github.sha }}
          path: |
            ./src/validations/report/schematron/**/*.*
            ./src/validations/report/test/**/*.*
          if-no-files-found: error
